import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-gray-100">

        {/* NAVBAR GLOBAL */}
        <nav className="bg-green-700 text-white shadow">
          <div className="max-w-6xl mx-auto flex justify-between items-center p-4">
            <h1 className="text-xl font-bold">Esporte do Norte</h1>

            <div className="flex gap-6 text-sm">
              <a href="/">Home</a>
              <a href="/times">Times</a>
              <a href="/campeonatos">Campeonatos</a>
              <a href="/estatisticas">Estatísticas</a>
            </div>
          </div>
        </nav>

        {/* CONTEÚDO */}
        <main className="max-w-6xl mx-auto p-6">
          {children}
        </main>

      </body>
    </html>
  );
}
